DROP TABLE IF EXISTS directory_podcast_directory_search;
DROP TABLE IF EXISTS directory_podcast_exception;
DROP TABLE IF EXISTS directory_search;
DROP TABLE IF EXISTS directory_podcast;
DROP TABLE IF EXISTS directory;
DROP TABLE IF EXISTS episode;
DROP TABLE IF EXISTS podcast_feed_content;
DROP TABLE IF EXISTS podcast_feed_location;
DROP TABLE IF EXISTS podcast;
