#!/bin/bash -e

#
# Install to: .git/hooks/
#

# Doesn't currently work because rustup doesn't pass through arguments passed
# "--": https://github.com/rust-lang-nursery/rustfmt/issues/2279
rustup run nightly cargo fmt -- --write-mode=diff
